<?= $this->doctype();?> 
<html>
    <head>
        <?
        echo $this->headTitle(); 
        echo $this->headMeta();
        echo $this->headScript();
        echo $this->headLink();
        ?>
    </head>
    <body>
        <div class="container">
            <div class="header">
            </div>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container" style="width: auto">
                    <a class="brand" href="/">
                        Zend Project
                    </a>
                    <div class="nav-collapse">
                    </div>
                </div>
            </div>
        </div>
        <?=$this->layout()->content;?> 
        <hr/>
            <div class="footer">
              © Zend Project <?= date('Y') ?>
            </div>
        </div>
    </body>
</html>